"""3revision

Revision ID: a08715f7e5d1
Revises: d63b85c3ad5e
Create Date: 2024-08-30 17:35:20.632252

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a08715f7e5d1"
down_revision: Union[str, None] = "d63b85c3ad5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_username", table_name="users")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_users_username", "users", ["username"], unique=True)
    # ### end Alembic commands ###
