"""index revision

Revision ID: d63b85c3ad5e
Revises: f0253be5bf60
Create Date: 2024-08-30 16:36:49.145760

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d63b85c3ad5e"
down_revision: Union[str, None] = "f0253be5bf60"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_articles_category", table_name="articles")
    op.drop_index("ix_articles_title", table_name="articles")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_articles_title", "articles", ["title"], unique=False)
    op.create_index("ix_articles_category", "articles", ["category"], unique=True)
    # ### end Alembic commands ###
